export const iconMap = {
  '0': 'wi wi-day-sunny',
  '1': 'wi wi-day-cloudy',
  '2': 'wi wi-day-cloudy-high',
  '3': 'wi wi-cloud',
  '45': 'wi wi-fog',
  '48': 'wi wi-fog',
  '51': 'wi wi-sprinkle',
  '53': 'wi wi-sprinkle',
  '55': 'wi wi-sprinkle',
  '56': 'wi wi-sleet',
  '57': 'wi wi-sleet',
  '61': 'wi wi-rain',
  '63': 'wi wi-rain',
  '65': 'wi wi-rain',
  '66': 'wi wi-hail',
  '67': 'wi wi-hail',
  '71': 'wi wi-snow',
  '73': 'wi wi-snow',
  '75': 'wi wi-snow',
  '77': 'wi wi-snow',
  '80': 'wi wi-showers',
  '81': 'wi wi-showers',
  '82': 'wi wi-showers',
  '85': 'wi wi-snow',
  '86': 'wi wi-snow',
  '95': 'wi wi-storm-showers',
  '96': 'wi wi-storm-showers',
  '99': 'wi wi-storm-showers',
}

export const getIcon = (code) => iconMap[code];
