export const iconMap = {
  '0': 'ri-sun-fill',
  '1': 'ri-sun-cloudy-fill',
  '2': 'ri-cloudy-fill',
  '3': 'ri-cloudy-fill',
  '45': 'ri-foggy-fill',
  '48': 'ri-mist-fill',
  '51': 'ri-rainy-fill',
  '53': 'ri-rainy-fill',
  '55': 'ri-rainy-fill',
  '56': 'ri-drizzle-fill',
  '57': 'ri-drizzle-fill',
  '61': 'ri-drizzle-fill',
  '63': 'ri-drizzle-fill',
  '65': 'ri-drizzle-fill',
  '66': 'ri-showers-fill',
  '67': 'ri-showers-fill',
  '71': 'ri-snowy-fill',
  '73': 'ri-snowy-fill',
  '75': 'ri-snowy-fill',
  '77': 'ri-snowy-fill',
  '80': 'ri-heavy-showers-line',
  '81': 'ri-heavy-showers-line',
  '82': 'ri-heavy-showers-line',
  '85': 'ri-snowflake-fill',
  '86': 'ri-snowflake-fill',
  '95': 'ri-thunderstorms-fill',
  '96': 'ri-thunderstorms-fill',
  '99': 'ri-thunderstorms-fill',
}

export const getIcon = (code) => iconMap[code];
